[2022-08-06 19:37:46,622] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 19:37:46,639] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 19:37:46,639] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 19:37:46,639] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 19:37:46,639] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 19:37:46,658] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-16 00:00:00+00:00
[2022-08-06 19:37:46,664] {standard_task_runner.py:52} INFO - Started process 1714 to run task
[2022-08-06 19:37:46,667] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-16T00:00:00+00:00', '--job-id', '517', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmplhkrnsqd', '--error-file', '/tmp/tmpedqe_l1e']
[2022-08-06 19:37:46,668] {standard_task_runner.py:80} INFO - Job 517: Subtask second_task
[2022-08-06 19:37:46,752] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [running]> on host b29c168c1666
[2022-08-06 19:37:46,865] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-16T00:00:00+00:00
[2022-08-06 19:37:46,866] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 19:37:46,867] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 19:37:46,883] {subprocess.py:85} INFO - Output:
[2022-08-06 19:37:46,885] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 19:37:46,885] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 19:37:46,925] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220116T000000, start_date=20220806T193746, end_date=20220806T193746
[2022-08-06 19:37:46,959] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 19:37:47,002] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 21:51:40,739] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 21:51:40,755] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 21:51:40,755] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:51:40,756] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 21:51:40,756] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:51:40,775] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-16 00:00:00+00:00
[2022-08-06 21:51:40,782] {standard_task_runner.py:52} INFO - Started process 1904 to run task
[2022-08-06 21:51:40,786] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-16T00:00:00+00:00', '--job-id', '517', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpq_7xvfpl', '--error-file', '/tmp/tmpoy9jsy7m']
[2022-08-06 21:51:40,786] {standard_task_runner.py:80} INFO - Job 517: Subtask second_task
[2022-08-06 21:51:40,888] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [running]> on host c3f731879890
[2022-08-06 21:51:41,006] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-16T00:00:00+00:00
[2022-08-06 21:51:41,009] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 21:51:41,009] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 21:51:41,026] {subprocess.py:85} INFO - Output:
[2022-08-06 21:51:41,028] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 21:51:41,029] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 21:51:41,115] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220116T000000, start_date=20220806T215140, end_date=20220806T215141
[2022-08-06 21:51:41,158] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 21:51:41,212] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 21:57:04,582] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 21:57:04,598] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 21:57:04,598] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:57:04,598] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 21:57:04,598] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:57:04,621] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-16 00:00:00+00:00
[2022-08-06 21:57:04,628] {standard_task_runner.py:52} INFO - Started process 1706 to run task
[2022-08-06 21:57:04,630] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-16T00:00:00+00:00', '--job-id', '521', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp83vf_x8s', '--error-file', '/tmp/tmpf4s_mmdr']
[2022-08-06 21:57:04,630] {standard_task_runner.py:80} INFO - Job 521: Subtask second_task
[2022-08-06 21:57:04,711] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [running]> on host bc7e154a4fdd
[2022-08-06 21:57:04,834] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-16T00:00:00+00:00
[2022-08-06 21:57:04,835] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 21:57:04,836] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 21:57:04,856] {subprocess.py:85} INFO - Output:
[2022-08-06 21:57:04,856] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 21:57:04,856] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 21:57:04,904] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220116T000000, start_date=20220806T215704, end_date=20220806T215704
[2022-08-06 21:57:04,962] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 21:57:05,016] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 22:12:05,358] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 22:12:05,371] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 22:12:05,371] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:12:05,371] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 22:12:05,371] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:12:05,392] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-16 00:00:00+00:00
[2022-08-06 22:12:05,399] {standard_task_runner.py:52} INFO - Started process 1705 to run task
[2022-08-06 22:12:05,401] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-16T00:00:00+00:00', '--job-id', '516', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmph8x1m_ta', '--error-file', '/tmp/tmpb_jnsc3j']
[2022-08-06 22:12:05,402] {standard_task_runner.py:80} INFO - Job 516: Subtask second_task
[2022-08-06 22:12:05,473] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [running]> on host 1250c3b659cd
[2022-08-06 22:12:05,562] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-16T00:00:00+00:00
[2022-08-06 22:12:05,563] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 22:12:05,564] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 22:12:05,581] {subprocess.py:85} INFO - Output:
[2022-08-06 22:12:05,583] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 22:12:05,583] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 22:12:05,621] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220116T000000, start_date=20220806T221205, end_date=20220806T221205
[2022-08-06 22:12:05,653] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 22:12:05,722] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 22:23:25,679] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 22:23:25,693] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-08-06 22:23:25,693] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:23:25,693] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 22:23:25,693] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:23:25,712] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-16 00:00:00+00:00
[2022-08-06 22:23:25,720] {standard_task_runner.py:52} INFO - Started process 1755 to run task
[2022-08-06 22:23:25,723] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-16T00:00:00+00:00', '--job-id', '518', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpeab0nkz0', '--error-file', '/tmp/tmpct0xq9lo']
[2022-08-06 22:23:25,723] {standard_task_runner.py:80} INFO - Job 518: Subtask second_task
[2022-08-06 22:23:25,793] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-16T00:00:00+00:00 [running]> on host b215076695c3
[2022-08-06 22:23:25,876] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-16T00:00:00+00:00
[2022-08-06 22:23:25,878] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 22:23:25,878] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 22:23:25,892] {subprocess.py:85} INFO - Output:
[2022-08-06 22:23:25,894] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 22:23:25,894] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 22:23:25,923] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220116T000000, start_date=20220806T222325, end_date=20220806T222325
[2022-08-06 22:23:25,975] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 22:23:26,003] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
