[2022-08-06 19:36:11,054] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 19:36:11,071] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 19:36:11,071] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 19:36:11,071] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 19:36:11,071] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 19:36:11,094] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2021-08-18 00:00:00+00:00
[2022-08-06 19:36:11,101] {standard_task_runner.py:52} INFO - Started process 280 to run task
[2022-08-06 19:36:11,105] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-18T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmplu9vdute', '--error-file', '/tmp/tmpcwxtuc8o']
[2022-08-06 19:36:11,105] {standard_task_runner.py:80} INFO - Job 63: Subtask second_task
[2022-08-06 19:36:11,195] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [running]> on host b29c168c1666
[2022-08-06 19:36:11,320] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-18T00:00:00+00:00
[2022-08-06 19:36:11,321] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 19:36:11,321] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 19:36:11,340] {subprocess.py:85} INFO - Output:
[2022-08-06 19:36:11,342] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 19:36:11,342] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 19:36:11,398] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210818T000000, start_date=20220806T193611, end_date=20220806T193611
[2022-08-06 19:36:11,437] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 19:36:11,497] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 21:50:06,325] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 21:50:06,336] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 21:50:06,337] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:50:06,337] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 21:50:06,337] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:50:06,354] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2021-08-18 00:00:00+00:00
[2022-08-06 21:50:06,360] {standard_task_runner.py:52} INFO - Started process 469 to run task
[2022-08-06 21:50:06,363] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-18T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpre559zya', '--error-file', '/tmp/tmpomm4s7_p']
[2022-08-06 21:50:06,363] {standard_task_runner.py:80} INFO - Job 61: Subtask second_task
[2022-08-06 21:50:06,445] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [running]> on host c3f731879890
[2022-08-06 21:50:06,584] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-18T00:00:00+00:00
[2022-08-06 21:50:06,585] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 21:50:06,586] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 21:50:06,606] {subprocess.py:85} INFO - Output:
[2022-08-06 21:50:06,608] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 21:50:06,609] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 21:50:06,651] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210818T000000, start_date=20220806T215006, end_date=20220806T215006
[2022-08-06 21:50:06,695] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 21:50:06,771] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 21:55:37,697] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 21:55:37,714] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 21:55:37,715] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:55:37,715] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 21:55:37,715] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:55:37,731] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2021-08-18 00:00:00+00:00
[2022-08-06 21:55:37,738] {standard_task_runner.py:52} INFO - Started process 282 to run task
[2022-08-06 21:55:37,741] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-18T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp6xm76f6t', '--error-file', '/tmp/tmpwe8uzkr8']
[2022-08-06 21:55:37,742] {standard_task_runner.py:80} INFO - Job 67: Subtask second_task
[2022-08-06 21:55:37,845] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [running]> on host bc7e154a4fdd
[2022-08-06 21:55:37,964] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-18T00:00:00+00:00
[2022-08-06 21:55:37,965] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 21:55:37,965] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 21:55:37,977] {subprocess.py:85} INFO - Output:
[2022-08-06 21:55:37,978] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 21:55:37,979] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 21:55:38,006] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210818T000000, start_date=20220806T215537, end_date=20220806T215538
[2022-08-06 21:55:38,034] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 21:55:38,087] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 22:10:36,563] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 22:10:36,587] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 22:10:36,587] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:10:36,587] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 22:10:36,587] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:10:36,609] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2021-08-18 00:00:00+00:00
[2022-08-06 22:10:36,617] {standard_task_runner.py:52} INFO - Started process 278 to run task
[2022-08-06 22:10:36,621] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-18T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp314v_1m2', '--error-file', '/tmp/tmp82hyn5ms']
[2022-08-06 22:10:36,621] {standard_task_runner.py:80} INFO - Job 64: Subtask second_task
[2022-08-06 22:10:36,699] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [running]> on host 1250c3b659cd
[2022-08-06 22:10:36,788] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-18T00:00:00+00:00
[2022-08-06 22:10:36,789] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 22:10:36,789] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 22:10:36,807] {subprocess.py:85} INFO - Output:
[2022-08-06 22:10:36,809] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 22:10:36,810] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 22:10:36,848] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210818T000000, start_date=20220806T221036, end_date=20220806T221036
[2022-08-06 22:10:36,913] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 22:10:36,954] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 22:18:23,864] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 22:18:23,878] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 22:18:23,878] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:18:23,878] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 22:18:23,878] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:18:23,901] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2021-08-18 00:00:00+00:00
[2022-08-06 22:18:23,909] {standard_task_runner.py:52} INFO - Started process 293 to run task
[2022-08-06 22:18:23,913] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-18T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpmx27cky7', '--error-file', '/tmp/tmpzqn3zx5o']
[2022-08-06 22:18:23,913] {standard_task_runner.py:80} INFO - Job 64: Subtask second_task
[2022-08-06 22:18:24,006] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [running]> on host ed53bde1c44a
[2022-08-06 22:18:24,089] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-18T00:00:00+00:00
[2022-08-06 22:18:24,090] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 22:18:24,091] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 22:18:24,105] {subprocess.py:85} INFO - Output:
[2022-08-06 22:18:24,106] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 22:18:24,106] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 22:18:24,142] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210818T000000, start_date=20220806T221823, end_date=20220806T221824
[2022-08-06 22:18:24,170] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 22:18:24,203] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 22:21:57,513] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 22:21:57,532] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [queued]>
[2022-08-06 22:21:57,533] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:21:57,533] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 22:21:57,533] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:21:57,554] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2021-08-18 00:00:00+00:00
[2022-08-06 22:21:57,561] {standard_task_runner.py:52} INFO - Started process 331 to run task
[2022-08-06 22:21:57,564] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-18T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpfioksex4', '--error-file', '/tmp/tmp_dguoe9z']
[2022-08-06 22:21:57,564] {standard_task_runner.py:80} INFO - Job 65: Subtask second_task
[2022-08-06 22:21:57,628] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-18T00:00:00+00:00 [running]> on host b215076695c3
[2022-08-06 22:21:57,712] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-18T00:00:00+00:00
[2022-08-06 22:21:57,713] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 22:21:57,713] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 22:21:57,730] {subprocess.py:85} INFO - Output:
[2022-08-06 22:21:57,733] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 22:21:57,733] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 22:21:57,768] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210818T000000, start_date=20220806T222157, end_date=20220806T222157
[2022-08-06 22:21:57,815] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 22:21:57,861] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
