[2022-08-06 22:23:05,592] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task manual__2022-08-06T22:23:04.140720+00:00 [queued]>
[2022-08-06 22:23:05,605] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task manual__2022-08-06T22:23:04.140720+00:00 [queued]>
[2022-08-06 22:23:05,605] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:23:05,605] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 22:23:05,606] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:23:05,623] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-08-06 22:23:04.140720+00:00
[2022-08-06 22:23:05,629] {standard_task_runner.py:52} INFO - Started process 1443 to run task
[2022-08-06 22:23:05,632] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'manual__2022-08-06T22:23:04.140720+00:00', '--job-id', '418', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp8wfu1626', '--error-file', '/tmp/tmp_12djf3k']
[2022-08-06 22:23:05,632] {standard_task_runner.py:80} INFO - Job 418: Subtask second_task
[2022-08-06 22:23:05,701] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task manual__2022-08-06T22:23:04.140720+00:00 [running]> on host b215076695c3
[2022-08-06 22:23:05,793] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-06T22:23:04.140720+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-06T22:23:04.140720+00:00
[2022-08-06 22:23:05,794] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 22:23:05,795] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 22:23:05,809] {subprocess.py:85} INFO - Output:
[2022-08-06 22:23:05,811] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 22:23:05,811] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 22:23:05,850] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220806T222304, start_date=20220806T222305, end_date=20220806T222305
[2022-08-06 22:23:05,883] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 22:23:05,925] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
