[2022-08-06 19:37:47,068] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 19:37:47,082] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 19:37:47,082] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 19:37:47,082] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 19:37:47,083] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 19:37:47,101] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-18 00:00:00+00:00
[2022-08-06 19:37:47,107] {standard_task_runner.py:52} INFO - Started process 1724 to run task
[2022-08-06 19:37:47,109] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-18T00:00:00+00:00', '--job-id', '520', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpo10jpo2x', '--error-file', '/tmp/tmpvlqno66y']
[2022-08-06 19:37:47,110] {standard_task_runner.py:80} INFO - Job 520: Subtask second_task
[2022-08-06 19:37:47,180] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [running]> on host b29c168c1666
[2022-08-06 19:37:47,268] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-18T00:00:00+00:00
[2022-08-06 19:37:47,269] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 19:37:47,269] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 19:37:47,281] {subprocess.py:85} INFO - Output:
[2022-08-06 19:37:47,283] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 19:37:47,283] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 19:37:47,317] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220118T000000, start_date=20220806T193747, end_date=20220806T193747
[2022-08-06 19:37:47,361] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 19:37:47,392] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 21:51:41,044] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 21:51:41,060] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 21:51:41,060] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:51:41,060] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 21:51:41,060] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:51:41,076] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-18 00:00:00+00:00
[2022-08-06 21:51:41,082] {standard_task_runner.py:52} INFO - Started process 1917 to run task
[2022-08-06 21:51:41,085] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-18T00:00:00+00:00', '--job-id', '520', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpn1w5dxfi', '--error-file', '/tmp/tmp8idu9w29']
[2022-08-06 21:51:41,085] {standard_task_runner.py:80} INFO - Job 520: Subtask second_task
[2022-08-06 21:51:41,165] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [running]> on host c3f731879890
[2022-08-06 21:51:41,287] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-18T00:00:00+00:00
[2022-08-06 21:51:41,288] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 21:51:41,288] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 21:51:41,307] {subprocess.py:85} INFO - Output:
[2022-08-06 21:51:41,308] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 21:51:41,309] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 21:51:41,363] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220118T000000, start_date=20220806T215141, end_date=20220806T215141
[2022-08-06 21:51:41,416] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 21:51:41,454] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 21:57:04,990] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 21:57:05,014] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 21:57:05,014] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:57:05,014] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 21:57:05,014] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 21:57:05,036] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-18 00:00:00+00:00
[2022-08-06 21:57:05,043] {standard_task_runner.py:52} INFO - Started process 1723 to run task
[2022-08-06 21:57:05,047] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-18T00:00:00+00:00', '--job-id', '525', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp1v3ifhc_', '--error-file', '/tmp/tmpm_gkjv03']
[2022-08-06 21:57:05,048] {standard_task_runner.py:80} INFO - Job 525: Subtask second_task
[2022-08-06 21:57:05,156] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [running]> on host bc7e154a4fdd
[2022-08-06 21:57:05,325] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-18T00:00:00+00:00
[2022-08-06 21:57:05,326] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 21:57:05,326] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 21:57:05,344] {subprocess.py:85} INFO - Output:
[2022-08-06 21:57:05,346] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 21:57:05,347] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 21:57:05,434] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220118T000000, start_date=20220806T215704, end_date=20220806T215705
[2022-08-06 21:57:05,500] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 21:57:05,549] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 22:12:05,792] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 22:12:05,811] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 22:12:05,811] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:12:05,812] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 22:12:05,812] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:12:05,826] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-18 00:00:00+00:00
[2022-08-06 22:12:05,832] {standard_task_runner.py:52} INFO - Started process 1717 to run task
[2022-08-06 22:12:05,834] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-18T00:00:00+00:00', '--job-id', '521', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpes4y7yjo', '--error-file', '/tmp/tmpu51ka4cb']
[2022-08-06 22:12:05,834] {standard_task_runner.py:80} INFO - Job 521: Subtask second_task
[2022-08-06 22:12:05,890] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [running]> on host 1250c3b659cd
[2022-08-06 22:12:05,968] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-18T00:00:00+00:00
[2022-08-06 22:12:05,969] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 22:12:05,970] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 22:12:06,011] {subprocess.py:85} INFO - Output:
[2022-08-06 22:12:06,012] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 22:12:06,013] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 22:12:06,044] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220118T000000, start_date=20220806T221205, end_date=20220806T221206
[2022-08-06 22:12:06,085] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 22:12:06,114] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-06 22:23:28,972] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 22:23:28,989] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [queued]>
[2022-08-06 22:23:28,989] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:23:28,989] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-06 22:23:28,989] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-06 22:23:29,007] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-01-18 00:00:00+00:00
[2022-08-06 22:23:29,015] {standard_task_runner.py:52} INFO - Started process 1795 to run task
[2022-08-06 22:23:29,019] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-01-18T00:00:00+00:00', '--job-id', '528', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpzjm5x9fc', '--error-file', '/tmp/tmp9hlmaqfr']
[2022-08-06 22:23:29,020] {standard_task_runner.py:80} INFO - Job 528: Subtask second_task
[2022-08-06 22:23:29,124] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-01-18T00:00:00+00:00 [running]> on host b215076695c3
[2022-08-06 22:23:29,242] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-18T00:00:00+00:00
[2022-08-06 22:23:29,244] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-06 22:23:29,244] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-08-06 22:23:29,263] {subprocess.py:85} INFO - Output:
[2022-08-06 22:23:29,265] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-08-06 22:23:29,265] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-06 22:23:29,348] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220118T000000, start_date=20220806T222328, end_date=20220806T222329
[2022-08-06 22:23:29,391] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-06 22:23:29,439] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
